BEGIN;

CREATE TABLE IF NOT EXISTS order_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL,
    order_number integer NOT NULL,
    user_id integer NOT NULL,
    event_type varchar(50) NOT NULL,
    result varchar(20) NOT NULL,
    message varchar(500),
    occurred_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_order_audit_order_id ON order_audit (order_id);
CREATE INDEX IF NOT EXISTS idx_order_audit_occurred_at ON order_audit (occurred_at);

COMMIT;
