spring.application.name=POS Backend API
# Base de datos local (SQLite)
db.local.url=jdbc:sqlite:./data/pos_local.db

# Base de datos remota (MySQL)
db.remote.url=jdbc:mysql://localhost:3306/fastfoodBD?serverTimezone=UTC&useSSL=false
db.remote.user=myadmin
db.remote.pass=myadmin

# Pool de conexiones
db.pool.max=10

# profile
spring.profiles.active=dev