spring.application.name=POS Backend API

# Por defecto trabajamos contra PostgreSQL local.
spring.profiles.default=local

# Pool de conexiones
db.pool.max=10
db.pool.connection-timeout=30000
db.pool.initialization-fail-timeout=-1
