BEGIN;

DROP SCHEMA IF EXISTS pos CASCADE;
CREATE SCHEMA pos;

SET search_path TO pos, public;

CREATE TABLE store (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(20) NOT NULL UNIQUE,
    name varchar(120) NOT NULL,
    phone varchar(20),
    timezone_name varchar(50) NOT NULL DEFAULT 'America/La_Paz',
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE person (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(100) NOT NULL,
    paternal_last_name varchar(100) NOT NULL,
    maternal_last_name varchar(100),
    phone varchar(20),
    email varchar(120),
    document_number varchar(30),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_person_email UNIQUE (email),
    CONSTRAINT uq_person_document_number UNIQUE (document_number)
);

CREATE TABLE role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(30) NOT NULL UNIQUE,
    name varchar(60) NOT NULL UNIQUE
);

CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(45) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    person_id bigint NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    last_login_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_app_user_person
        FOREIGN KEY (person_id) REFERENCES person (id),
    CONSTRAINT uq_app_user_person UNIQUE (person_id)
);

CREATE TABLE user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE
);

CREATE TABLE category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(255),
    display_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_category_store
        FOREIGN KEY (store_id) REFERENCES store (id) ON DELETE CASCADE,
    CONSTRAINT chk_category_display_order_non_negative CHECK (display_order >= 0),
    CONSTRAINT uq_category_id_store UNIQUE (id, store_id),
    CONSTRAINT uq_category_store_name UNIQUE (store_id, name)
);

CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    category_id bigint NOT NULL,
    sku varchar(30),
    name varchar(120) NOT NULL,
    description varchar(255),
    price numeric(10,2) NOT NULL,
    cost numeric(10,2) NOT NULL DEFAULT 0,
    track_inventory boolean NOT NULL DEFAULT false,
    stock_quantity numeric(12,3),
    prep_time_minutes integer NOT NULL DEFAULT 0,
    status varchar(15) NOT NULL DEFAULT 'ACTIVO',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_store
        FOREIGN KEY (store_id) REFERENCES store (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id, store_id) REFERENCES category (id, store_id),
    CONSTRAINT chk_product_price_non_negative CHECK (price >= 0),
    CONSTRAINT chk_product_cost_non_negative CHECK (cost >= 0),
    CONSTRAINT chk_product_stock_non_negative CHECK (stock_quantity IS NULL OR stock_quantity >= 0),
    CONSTRAINT chk_product_prep_time_non_negative CHECK (prep_time_minutes >= 0),
    CONSTRAINT chk_product_status
        CHECK (status IN ('ACTIVO', 'INACTIVO', 'AGOTADO')),
    CONSTRAINT uq_product_store_sku UNIQUE (store_id, sku)
);

CREATE TABLE order_status (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(30) NOT NULL UNIQUE,
    name varchar(60) NOT NULL UNIQUE
);

CREATE TABLE payment_method (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(30) NOT NULL UNIQUE,
    name varchar(60) NOT NULL UNIQUE,
    requires_reference boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE cash_register_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    opened_by_user_id bigint NOT NULL,
    closed_by_user_id bigint,
    opening_amount numeric(10,2) NOT NULL DEFAULT 0,
    expected_amount numeric(10,2),
    closing_amount numeric(10,2),
    status varchar(15) NOT NULL DEFAULT 'ABIERTA',
    opened_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cash_register_session_store
        FOREIGN KEY (store_id) REFERENCES store (id),
    CONSTRAINT fk_cash_register_session_opened_by
        FOREIGN KEY (opened_by_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_cash_register_session_closed_by
        FOREIGN KEY (closed_by_user_id) REFERENCES app_user (id),
    CONSTRAINT chk_cash_register_session_opening_amount_non_negative CHECK (opening_amount >= 0),
    CONSTRAINT chk_cash_register_session_expected_amount_non_negative CHECK (expected_amount IS NULL OR expected_amount >= 0),
    CONSTRAINT chk_cash_register_session_closing_amount_non_negative CHECK (closing_amount IS NULL OR closing_amount >= 0),
    CONSTRAINT chk_cash_register_session_status CHECK (status IN ('ABIERTA', 'CERRADA', 'DESCUADRADA')),
    CONSTRAINT uq_cash_register_session_id_store UNIQUE (id, store_id)
);

CREATE TABLE daily_order_counter (
    store_id bigint NOT NULL,
    business_date date NOT NULL,
    last_value integer NOT NULL DEFAULT 0,
    PRIMARY KEY (store_id, business_date),
    CONSTRAINT fk_daily_order_counter_store
        FOREIGN KEY (store_id) REFERENCES store (id) ON DELETE CASCADE,
    CONSTRAINT chk_daily_order_counter_last_value_non_negative CHECK (last_value >= 0)
);

CREATE TABLE sales_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    cash_session_id bigint,
    business_date date NOT NULL DEFAULT CURRENT_DATE,
    order_number integer,
    channel varchar(20) NOT NULL DEFAULT 'MOSTRADOR',
    status_id bigint NOT NULL,
    customer_name varchar(120),
    notes varchar(255),
    subtotal numeric(10,2) NOT NULL DEFAULT 0,
    discount_total numeric(10,2) NOT NULL DEFAULT 0,
    tax_total numeric(10,2) NOT NULL DEFAULT 0,
    total numeric(10,2) GENERATED ALWAYS AS (subtotal - discount_total + tax_total) STORED,
    paid_total numeric(10,2) NOT NULL DEFAULT 0,
    balance_due numeric(10,2) GENERATED ALWAYS AS (GREATEST((subtotal - discount_total + tax_total) - paid_total, 0::numeric)) STORED,
    payment_status varchar(15) NOT NULL DEFAULT 'PENDIENTE',
    created_by_user_id bigint NOT NULL,
    placed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sales_order_store
        FOREIGN KEY (store_id) REFERENCES store (id),
    CONSTRAINT fk_sales_order_cash_session
        FOREIGN KEY (cash_session_id, store_id) REFERENCES cash_register_session (id, store_id),
    CONSTRAINT fk_sales_order_status
        FOREIGN KEY (status_id) REFERENCES order_status (id),
    CONSTRAINT fk_sales_order_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES app_user (id),
    CONSTRAINT chk_sales_order_order_number_positive CHECK (order_number IS NULL OR order_number > 0),
    CONSTRAINT chk_sales_order_channel
        CHECK (channel IN ('MOSTRADOR', 'LLEVAR', 'DELIVERY', 'APP')),
    CONSTRAINT chk_sales_order_subtotal_non_negative CHECK (subtotal >= 0),
    CONSTRAINT chk_sales_order_discount_non_negative CHECK (discount_total >= 0),
    CONSTRAINT chk_sales_order_tax_non_negative CHECK (tax_total >= 0),
    CONSTRAINT chk_sales_order_paid_total_non_negative CHECK (paid_total >= 0),
    CONSTRAINT chk_sales_order_total_not_negative CHECK ((subtotal + tax_total) >= discount_total),
    CONSTRAINT chk_sales_order_payment_status CHECK (payment_status IN ('PENDIENTE', 'PARCIAL', 'PAGADO')),
    CONSTRAINT uq_sales_order_business_number UNIQUE (store_id, business_date, order_number)
);

CREATE TABLE sales_order_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id bigint NOT NULL,
    line_number integer,
    product_id bigint NOT NULL,
    product_name varchar(120) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL DEFAULT 0,
    notes varchar(255),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sales_order_item_order
        FOREIGN KEY (sales_order_id) REFERENCES sales_order (id) ON DELETE CASCADE,
    CONSTRAINT fk_sales_order_item_product
        FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT chk_sales_order_item_line_number_positive CHECK (line_number IS NULL OR line_number > 0),
    CONSTRAINT chk_sales_order_item_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_sales_order_item_unit_price_non_negative CHECK (unit_price >= 0),
    CONSTRAINT chk_sales_order_item_subtotal_non_negative CHECK (subtotal >= 0),
    CONSTRAINT uq_sales_order_item_line UNIQUE (sales_order_id, line_number)
);

CREATE TABLE sales_order_payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id bigint NOT NULL,
    payment_method_id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    reference_code varchar(100),
    status varchar(15) NOT NULL DEFAULT 'APLICADO',
    paid_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    received_by_user_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sales_order_payment_order
        FOREIGN KEY (sales_order_id) REFERENCES sales_order (id) ON DELETE CASCADE,
    CONSTRAINT fk_sales_order_payment_method
        FOREIGN KEY (payment_method_id) REFERENCES payment_method (id),
    CONSTRAINT fk_sales_order_payment_received_by
        FOREIGN KEY (received_by_user_id) REFERENCES app_user (id),
    CONSTRAINT chk_sales_order_payment_amount_positive CHECK (amount > 0),
    CONSTRAINT chk_sales_order_payment_status CHECK (status IN ('APLICADO', 'ANULADO'))
);

CREATE OR REPLACE FUNCTION pos.touch_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION pos.assign_daily_order_number()
RETURNS trigger AS $$
BEGIN
    IF NEW.business_date IS NULL THEN
        NEW.business_date = CURRENT_DATE;
    END IF;

    IF NEW.order_number IS NULL OR NEW.order_number = 0 THEN
        INSERT INTO pos.daily_order_counter (store_id, business_date, last_value)
        VALUES (NEW.store_id, NEW.business_date, 1)
        ON CONFLICT (store_id, business_date)
        DO UPDATE SET last_value = pos.daily_order_counter.last_value + 1
        RETURNING last_value INTO NEW.order_number;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION pos.prepare_sales_order_item()
RETURNS trigger AS $$
DECLARE
    v_product_name varchar(120);
    v_product_price numeric(10,2);
    v_product_store_id bigint;
    v_order_store_id bigint;
BEGIN
    SELECT p.name, p.price, p.store_id
    INTO v_product_name, v_product_price, v_product_store_id
    FROM pos.product p
    WHERE p.id = NEW.product_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Product % does not exist', NEW.product_id;
    END IF;

    SELECT so.store_id
    INTO v_order_store_id
    FROM pos.sales_order so
    WHERE so.id = NEW.sales_order_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Sales order % does not exist', NEW.sales_order_id;
    END IF;

    IF v_product_store_id <> v_order_store_id THEN
        RAISE EXCEPTION 'Product % does not belong to store of sales order %', NEW.product_id, NEW.sales_order_id;
    END IF;

    IF NEW.line_number IS NULL THEN
        SELECT COALESCE(MAX(soi.line_number), 0) + 1
        INTO NEW.line_number
        FROM pos.sales_order_item soi
        WHERE soi.sales_order_id = NEW.sales_order_id;
    END IF;

    IF NEW.product_name IS NULL OR btrim(NEW.product_name) = '' THEN
        NEW.product_name = v_product_name;
    END IF;

    IF NEW.unit_price IS NULL THEN
        NEW.unit_price = v_product_price;
    END IF;

    NEW.subtotal = round(NEW.quantity * NEW.unit_price, 2);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION pos.refresh_sales_order_totals(p_sales_order_id bigint)
RETURNS void AS $$
DECLARE
    v_subtotal numeric(10,2);
    v_paid_total numeric(10,2);
    v_discount_total numeric(10,2);
    v_tax_total numeric(10,2);
    v_total numeric(10,2);
BEGIN
    SELECT COALESCE(SUM(soi.subtotal), 0)
    INTO v_subtotal
    FROM pos.sales_order_item soi
    WHERE soi.sales_order_id = p_sales_order_id;

    SELECT COALESCE(SUM(sop.amount), 0)
    INTO v_paid_total
    FROM pos.sales_order_payment sop
    WHERE sop.sales_order_id = p_sales_order_id
      AND sop.status = 'APLICADO';

    SELECT so.discount_total, so.tax_total
    INTO v_discount_total, v_tax_total
    FROM pos.sales_order so
    WHERE so.id = p_sales_order_id;

    v_total = round(v_subtotal - v_discount_total + v_tax_total, 2);

    UPDATE pos.sales_order so
    SET subtotal = v_subtotal,
        paid_total = v_paid_total,
        payment_status = CASE
            WHEN v_total <= 0 THEN 'PAGADO'
            WHEN v_paid_total <= 0 THEN 'PENDIENTE'
            WHEN v_paid_total < v_total THEN 'PARCIAL'
            ELSE 'PAGADO'
        END,
        updated_at = CURRENT_TIMESTAMP
    WHERE so.id = p_sales_order_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION pos.sync_sales_order_totals()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM pos.refresh_sales_order_totals(OLD.sales_order_id);
        RETURN OLD;
    END IF;

    PERFORM pos.refresh_sales_order_totals(NEW.sales_order_id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION pos.validate_sales_order_payment()
RETURNS trigger AS $$
DECLARE
    v_requires_reference boolean;
BEGIN
    SELECT pm.requires_reference
    INTO v_requires_reference
    FROM pos.payment_method pm
    WHERE pm.id = NEW.payment_method_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Payment method % does not exist', NEW.payment_method_id;
    END IF;

    IF v_requires_reference AND (NEW.reference_code IS NULL OR btrim(NEW.reference_code) = '') THEN
        RAISE EXCEPTION 'Payment method % requires reference_code', NEW.payment_method_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER store_set_updated_at
BEFORE UPDATE ON store
FOR EACH ROW
EXECUTE FUNCTION pos.touch_updated_at();

CREATE TRIGGER person_set_updated_at
BEFORE UPDATE ON person
FOR EACH ROW
EXECUTE FUNCTION pos.touch_updated_at();

CREATE TRIGGER app_user_set_updated_at
BEFORE UPDATE ON app_user
FOR EACH ROW
EXECUTE FUNCTION pos.touch_updated_at();

CREATE TRIGGER category_set_updated_at
BEFORE UPDATE ON category
FOR EACH ROW
EXECUTE FUNCTION pos.touch_updated_at();

CREATE TRIGGER product_set_updated_at
BEFORE UPDATE ON product
FOR EACH ROW
EXECUTE FUNCTION pos.touch_updated_at();

CREATE TRIGGER cash_register_session_set_updated_at
BEFORE UPDATE ON cash_register_session
FOR EACH ROW
EXECUTE FUNCTION pos.touch_updated_at();

CREATE TRIGGER sales_order_set_updated_at
BEFORE UPDATE ON sales_order
FOR EACH ROW
EXECUTE FUNCTION pos.touch_updated_at();

CREATE TRIGGER sales_order_assign_daily_number
BEFORE INSERT ON sales_order
FOR EACH ROW
EXECUTE FUNCTION pos.assign_daily_order_number();

CREATE TRIGGER sales_order_item_prepare
BEFORE INSERT OR UPDATE ON sales_order_item
FOR EACH ROW
EXECUTE FUNCTION pos.prepare_sales_order_item();

CREATE TRIGGER sales_order_item_sync_order
AFTER INSERT OR UPDATE OR DELETE ON sales_order_item
FOR EACH ROW
EXECUTE FUNCTION pos.sync_sales_order_totals();

CREATE TRIGGER sales_order_payment_sync_order
AFTER INSERT OR UPDATE OR DELETE ON sales_order_payment
FOR EACH ROW
EXECUTE FUNCTION pos.sync_sales_order_totals();

CREATE TRIGGER sales_order_payment_validate
BEFORE INSERT OR UPDATE ON sales_order_payment
FOR EACH ROW
EXECUTE FUNCTION pos.validate_sales_order_payment();

CREATE UNIQUE INDEX ux_cash_register_session_one_open_per_store
    ON cash_register_session (store_id)
    WHERE status = 'ABIERTA';

CREATE INDEX idx_category_store_active
    ON category (store_id, is_active);

CREATE INDEX idx_product_category_status
    ON product (category_id, status);

CREATE INDEX idx_sales_order_status
    ON sales_order (status_id);

CREATE INDEX idx_sales_order_placed_at
    ON sales_order (placed_at);

CREATE INDEX idx_sales_order_created_by
    ON sales_order (created_by_user_id);

CREATE INDEX idx_sales_order_item_product
    ON sales_order_item (product_id);

CREATE INDEX idx_sales_order_payment_method
    ON sales_order_payment (payment_method_id);

COMMIT;
