-- PostgreSQL version of fastfoodbd.
-- Main adjustments from the MySQL dump:
-- 1. Replaces AUTO_INCREMENT with IDENTITY columns.
-- 2. Replaces unsigned numeric types with CHECK constraints.
-- 3. Replaces MySQL enum with varchar + CHECK for portability.
-- 4. Renames table "user" to "app_user" to avoid reserved-word issues.
-- 5. Replaces ON UPDATE CURRENT_TIMESTAMP with a trigger.

BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS order_detail CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS order_status CASCADE;
DROP TABLE IF EXISTS category CASCADE;

CREATE TABLE category (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    description varchar(255) DEFAULT ' ',
    status boolean,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER category_set_updated_at
BEFORE UPDATE ON category
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE order_status (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE person (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(100) NOT NULL,
    paternal_last_name varchar(100) NOT NULL,
    maternal_last_name varchar(100) DEFAULT ' ',
    phone varchar(20) DEFAULT ' ',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE app_user (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(45) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    person_id integer NOT NULL,
    CONSTRAINT fk_app_user_person
        FOREIGN KEY (person_id) REFERENCES person (id)
);

CREATE TABLE orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    total numeric(10,2) NOT NULL,
    order_number integer NOT NULL CHECK (order_number >= 0),
    user_id integer NOT NULL,
    status_id integer NOT NULL,
    CONSTRAINT chk_orders_total_positive CHECK (total >= 0),
    CONSTRAINT fk_orders_app_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_orders_order_status
        FOREIGN KEY (status_id) REFERENCES order_status (id)
);

CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_orders_status_id ON orders (status_id);

CREATE TABLE product (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    description varchar(255),
    price numeric(10,2) NOT NULL,
    stock integer,
    status varchar(10) NOT NULL DEFAULT 'ACTIVO',
    category_id integer NOT NULL,
    CONSTRAINT chk_product_price_positive CHECK (price >= 0),
    CONSTRAINT chk_product_stock_positive CHECK (stock IS NULL OR stock >= 0),
    CONSTRAINT chk_product_status
        CHECK (status IN ('ACTIVO', 'INACTIVO', 'AGOTADO')),
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE INDEX idx_product_category_id ON product (category_id);

CREATE TABLE order_detail (
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    PRIMARY KEY (order_id, product_id),
    CONSTRAINT chk_order_detail_quantity_positive CHECK (quantity >= 0),
    CONSTRAINT chk_order_detail_price_positive CHECK (price >= 0),
    CONSTRAINT chk_order_detail_subtotal_positive CHECK (subtotal >= 0),
    CONSTRAINT fk_order_detail_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_detail_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_detail_product_id ON order_detail (product_id);

CREATE TABLE user_role (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE INDEX idx_user_role_role_id ON user_role (role_id);

INSERT INTO category (id, name, description, status, created_at, updated_at) VALUES
    (1, 'Refrescos', 'Bebidas azucaradas o agua embotellada, frias o a temperatura ambiente.', true, '2025-10-13 20:24:12', '2025-10-13 20:24:12'),
    (3, 'Hamburguesas', 'Platillos principales a base de carne, pollo o opciones vegetarianas.', true, '2025-10-14 15:03:46', '2025-10-14 15:03:46');

INSERT INTO product (id, name, description, price, stock, status, category_id) VALUES
    (5, 'Coca-Cola', 'Refresco de cola de 355ml.', 18.50, 100, 'ACTIVO', 1),
    (6, 'Fanta Naranja', 'Refresco de naranja de 355ml.', 17.00, 75, 'ACTIVO', 1),
    (7, 'Agua Mineral', 'Botella de agua mineral de 500ml.', 12.00, 200, 'ACTIVO', 1),
    (8, 'Sprite', 'Refresco de limon de 355ml.', 17.50, 50, 'AGOTADO', 1),
    (10, 'Hamburguesa', 'Hamburguesa con queso', 5.99, 50, 'ACTIVO', 3);

SELECT setval(pg_get_serial_sequence('category', 'id'), COALESCE((SELECT MAX(id) FROM category), 1), true);
SELECT setval(pg_get_serial_sequence('order_status', 'id'), COALESCE((SELECT MAX(id) FROM order_status), 1), true);
SELECT setval(pg_get_serial_sequence('person', 'id'), COALESCE((SELECT MAX(id) FROM person), 1), true);
SELECT setval(pg_get_serial_sequence('role', 'id'), COALESCE((SELECT MAX(id) FROM role), 1), true);
SELECT setval(pg_get_serial_sequence('app_user', 'id'), COALESCE((SELECT MAX(id) FROM app_user), 1), true);
SELECT setval(pg_get_serial_sequence('orders', 'id'), COALESCE((SELECT MAX(id) FROM orders), 1), true);
SELECT setval(pg_get_serial_sequence('product', 'id'), COALESCE((SELECT MAX(id) FROM product), 1), true);

COMMIT;
